phrase = "Sanjay"
print("He does very good things " + phrase)
# Prefixed "" for HCS with space at end and for variable prefixed with + and space
print("His name is " + phrase)
print(phrase + " likes to eat mango")
# started with variable space + added HCS
print("He like to meet " +phrase)
print(phrase + " loves read.")
print("There is going to be a new company called "+phrase)
print(phrase)
print(phrase + " is cool")
print(phrase + " is going very strong,")
print(phrase + "there are 250 employees.")
print("Sanj\nay")
print("Ata\ncons Ltd.")
print(phrase + " is very great\ncompany ")
print("There is a \nbest company named " + phrase)
print(phrase.lower ())
print(phrase.upper())
print(phrase.lower())
print(phrase.isupper())
print(phrase.islower())
print(phrase.upper().isupper())
print(phrase.lower().islower())
print(len(phrase))
print(phrase.lower().islower())
print(phrase.lower().islower())
print(phrase.upper().isupper())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper())
print(phrase[5])
print(phrase.lower())
print(phrase.upper())
print(" There is a big company ")
print("I am Sanjay")
print(phrase.lower())
print(phrase.upper())
print(phrase.islower())
print(phrase.isupper())
print(phrase.upper().isupper())
print(phrase.lower().islower())
print(phrase.upper())
print(len(phrase))
print(phrase.index("S"))
print(phrase.index("j"))
print(phrase.upper())
print(phrase.lower())
print(phrase.islower())
print(phrase.lower().islower())